version: 2

project_name: reqman

builds:
  - id: reqman
    main: .
    binary: reqman
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - darwin_arm64
    ldflags:
      - -s -w

archives:
  - id: reqman
    ids:
      - reqman
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
